package ca.utoronto.cs.message;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.stream.Stream;

public enum MessageType {
	LOGIN_REQUEST(1),
	LOGOUT_REQUEST(2),
	JOIN_EVENT_REQUEST(3),
	LEAVE_EVENT_REQUEST(4),
	CREATE_EVENT_REQUEST(5),
	LIST_EVENTS_REQUEST(6),
	MESSAGE_SPEAKER_REQUEST(7),
	MESSAGE_FRIEND_REQUEST(8),
	BROADCAST_AUDIENCES_REQUEST(9),
	ADD_FRIEND_REQUEST(10),
	REMOVE_FRIEND_REQUEST(11),
	SAVE_REQUEST(12),
	CREATE_USER_ACCOUNT_REQUEST(13),
	DELETE_EVENT_REQUEST(14),
	CHANGE_SPEAKER_REQUEST(15),
	CHECK_ALL_MESSAGE_REQUEST(16),
	MESSAGE_EVENT_REQUEST(17),
	MESSAGE_ALL_SPEAKER_REQUEST(18),
	CREATE_ROOM_REQUEST(19),
	WHO_AM_I_REQUEST(20),
	GET_MESSAGE_REQUEST(21),
	/** Newly Added */
	LIST_ROOMS_REQUEST(22),
	DELETE_ROOM_REQUEST(23),
	CHANGE_EVENT_CAPACITY_REQUEST(24),
	UNKNOWN_REQUEST(99),


	BANNER(100),
	LOGIN_RESPONSE(101),
	LOGOUT_RESPONSE(102),
	JOIN_EVENT_RESPONSE(103),
	LEAVE_EVENT_RESPONSE(104),
	CREATE_EVENT_RESPONSE(105),
	LIST_EVENTS_RESPONSE(106),
	MESSAGE_SPEAKER_RESPONSE(107),
	MESSAGE_FRIEND_RESPONSE(108),
	BROADCAST_AUDIENCES_RESPONSE(109),
	ADD_FRIEND_RESPONSE(110),
	REMOVE_FRIEND_RESPONSE(111),
	SAVE_RESPONSE(112),
	MESSAGE_RESPONSE(113),
	CREATE_USER_ACCOUNT_RESPONSE(114),
	DELETE_EVENT_RESPONSE(115),
	CHANGE_SPEAKER_RESPONSE(116),
	CHECK_ALL_MESSAGE_RESPONSE(117),
	MESSAGE_EVENT_RESPONSE(118),
	MESSAGE_ALL_SPEAKER_RESPONSE(119),
	CREATE_ROOM_RESPONSE(120),
	WHO_AM_I_RESPONSE(121),
	GET_MESSAGE_RESPONSE(122),
	/** Newly Added */
	LIST_ROOMS_RESPONSE(123),
	DELETE_ROOM_RESPONSE(124),
	CHANGE_EVENT_CAPACITY_RESPONSE(125),
	UNKNOWN_RESPONSE(199),

	ERROR(900);

	private final int value;

	MessageType(final int newValue) {
		value = newValue;
	}

	@JsonValue
	public int getValue() { return value; }

	@JsonCreator
	public static MessageType fromValue(int value) {
		return Stream.of(MessageType.values()).filter(
				state -> state.value == value).findFirst().get();
	}
}
